CREATE DATABASE items;
CREATE USER root WITH PASSWORD 'root';
GRANT ALL PRIVILEGES ON DATABASE items to root;
CREATE TABLE ItemsStates
(
    ID SERIAL PRIMARY KEY,
    NAME CHARACTER VARYING(30)
);
CREATE TABLE ItemsCategories
(
    ID SERIAL PRIMARY KEY,
    NAME CHARACTER VARYING(30)
);
CREATE TABLE Attachs
(
    ID SERIAL PRIMARY KEY,
    LINK_TO_FILE CHARACTER VARYING(30)
);
CREATE TABLE Rules
(
    ID SERIAL PRIMARY KEY,
    NAME CHARACTER VARYING(30),
    POSSIBILITES CHARACTER VARYING(30)
);
CREATE TABLE Role
(
    ID SERIAL PRIMARY KEY,
    NAME CHARACTER VARYING(30)
);
CREATE TABLE RolesToRules
(
    ID SERIAL PRIMARY KEY,
    ROLE_ID INTEGER references Role(ID),
    RULE_ID INTEGER references Rules(ID)
);
CREATE TABLE Users
(
    ID SERIAL PRIMARY KEY,
    NAME CHARACTER VARYING(30),
    LAST_NAME CHARACTER VARYING(30),
    PASSWORD CHARACTER VARYING(30),
    ROLE_ID INTEGER references Role(ID)
);
CREATE TABLE Items
(
    ID SERIAL PRIMARY KEY,
    USER_ID INTEGER references Users(ID),
    CATEGORY_ID INTEGER references ItemsCategories(ID),
    STATE_ID INTEGER references ItemsStates(ID),
    FILE_ID INTEGER references Attachs(ID)
);
CREATE TABLE Comments
(
    ID SERIAL PRIMARY KEY,
    USER_ID INTEGER references Users(ID),
    FILE_ID INTEGER references Attachs(ID),
    ITEM_ID INTEGER references Items(ID),
    TEXT CHARACTER VARYING(500)
);
INSERT INTO Rules (ID, NAME, POSSIBILITES) VALUES (1, 'admin', 'see all');
INSERT INTO Role (NAME) VALUES ('admin');
INSERT INTO RolesToRules (ROLE_ID, RULE_ID) VALUES (1, 1);
INSERT INTO Users (NAME, LAST_NAME, PASSWORD, ROLE_ID) VALUES ('pavel', 'ch', 'root', 1);
INSERT INTO ItemsCategories (NAME) VALUES ('orders');
INSERT INTO ItemsCategories (NAME) VALUES ('products');
INSERT INTO ItemsStates (NAME) VALUES ('new');
INSERT INTO ItemsStates (NAME) VALUES ('process');
INSERT INTO ItemsStates (NAME) VALUES ('closed');
INSERT INTO Attachs (LINK_TO_FILE) VALUES ('/test.jpg');
INSERT INTO Attachs (LINK_TO_FILE) VALUES ('/test2.jpg');
INSERT INTO Attachs (LINK_TO_FILE) VALUES ('/test3.jpg');
INSERT INTO Items (USER_ID, CATEGORY_ID, STATE_ID, FILE_ID) VALUES (1, 2, 1, 3);
INSERT INTO Comments (USER_ID, FILE_ID, ITEM_ID, TEXT) VALUES (1, 0, 1, 'Столкнулся с проблемой');
INSERT INTO Comments (USER_ID, FILE_ID, ITEM_ID, TEXT) VALUES (1, 1, 1, 'Прикладываю файл');